"""
This type stub file was generated by pyright.
"""

from nodesample.nodes import Clock, MemberList, MemberStats, MessageLog, Room

def takes_room(r: Room) -> None:
    ...

def takes_log(l: MessageLog) -> None:
    ...

def takes_members(m: MemberList) -> None:
    ...

def takes_stats(s: MemberStats) -> None:
    ...

def takes_dict_str_bool(d: dict[str, bool]) -> None:
    ...

def takes_dict_str_int(d: dict[str, int]) -> None:
    ...

def takes_clock(c: Clock) -> None:
    ...

