"""
This type stub file was generated by pyright.
"""

from affairon import Node

class Clock:
    tick: int
    def advance(self) -> int:
        ...
    


class MemberList(Node):
    names: list[str]
    stats: MemberStats
    def join(self, name: str) -> dict[str, bool]:
        ...
    
    def kick(self, name: str) -> dict[str, bool]:
        ...
    


class Room(Node):
    log: MessageLog
    members: MemberList
    ...


class MemberStats(Node):
    counts: dict[str, int]
    def bump(self, name: str) -> dict[str, int]:
        ...
    


class MessageLog(Node):
    entries: list[dict[str, str | int]]
    def record(self, sender: str, text: str) -> dict[str, int]:
        ...
    


